Repository helidon-io/helidon-build-tools, pull requests merged in 2022-10, with the labels that each got.

#794 [helidon-maven-plugin] Improve module support
  maven-plugins/helidon-maven-plugin/README.md
  maven-plugins/helidon-maven-plugin/src/it/projects/module-test/expected4.log
  maven-plugins/helidon-maven-plugin/src/it/projects/module-test/expected5.log
  maven-plugins/helidon-maven-plugin/src/it/projects/module-test/expected6.log
  maven-plugins/helidon-maven-plugin/src/it/projects/module-test/invoker.properties
  maven-plugins/helidon-maven-plugin/src/it/projects/module-test/pom.xml
  maven-plugins/helidon-maven-plugin/src/it/projects/module-test/postbuild.groovy
  maven-plugins/helidon-maven-plugin/src/main/java/io/helidon/build/maven/GraalNativeMojo.java
  maven-plugins/helidon-maven-plugin/src/main/java/io/helidon/build/maven/component/PathComponent.java
  maven-plugins/helidon-maven-plugin/src/main/java/io/helidon/build/maven/component/package-info.java
Labels: maven-plugin, backport, 3.x

#796 Add "module" and "none" execution mode to readme
  helidon-maven-plugin/README.md
Labels: docs, 2.x

#802 2.x: Backport support for EPL2_PLUS_GPL2_CPE_ID
  licensing/src/main/java/io/helidon/build/licensing/Report.java
Labels: backport, 2.x

#804 3.x: Upgrade commons-text to 1.10.0
  pom.xml
Labels: OCA Verified

#805 2.x: Upgrade commons-text to 1.10.0
  pom.xml
Labels: OCA Verified

#809 3.x: Report nested exception when license report error
  licensing/src/main/java/io/helidon/build/licensing/Report.java
Labels: 3.x, OCA Verified

#808 2.x: Report nested exception when license report error
  licensing/src/main/java/io/helidon/build/licensing/Report.java
Labels: OCA Verified
