Repository helidon-io/helidon-build-tools, pull requests merged in 2022-12, with the labels that each got.

#822 Re-enable spotbugs
  .github/workflows/validate.yml
  archetype/engine-v1/etc/spotbugs/exclude.xml
  archetype/engine-v1/pom.xml
  archetype/engine-v2/etc/spotbugs/exclude.xml
  archetype/engine-v2/pom.xml
  cli/codegen/etc/spotbugs/exclude.xml
  cli/codegen/pom.xml
  cli/common/etc/spotbugs/exclude.xml
  cli/common/pom.xml
  cli/harness/etc/spotbugs/exclude.xml
  cli/harness/pom.xml
  cli/impl/etc/spotbugs/exclude.xml
  cli/impl/pom.xml
  cli/plugin/etc/spotbugs/exclude.xml
  cli/plugin/pom.xml
  common/ansi/etc/spotbugs/exclude.xml
  common/ansi/pom.xml
  common/common/etc/spotbugs/exclude.xml
  common/common/pom.xml
  common/markdown/etc/spotbugs/exclude.xml
  common/markdown/pom.xml
  common/maven/etc/spotbugs/exclude.xml
  common/maven/pom.xml
  common/test-utils/etc/spotbugs/exclude.xml
  common/test-utils/pom.xml
  common/test-utils/src/main/java/io/helidon/build/common/test/utils/JUnitLauncher.java
  common/xml/etc/spotbugs/exclude.xml
  common/xml/pom.xml
  dev-loop/dev-loop/etc/spotbugs/exclude.xml
  dev-loop/dev-loop/pom.xml
  etc/scripts/spotbugs.sh
  licensing/etc/spotbugs/exclude.xml
  licensing/pom.xml
  linker/etc/spotbugs/exclude.xml
  linker/pom.xml
  maven-plugins/helidon-archetype-maven-plugin/etc/spotbugs/exclude.xml
  maven-plugins/helidon-archetype-maven-plugin/pom.xml
  maven-plugins/services-maven-plugin/etc/spotbugs/exclude.xml
  maven-plugins/services-maven-plugin/pom.xml
  maven-plugins/snakeyaml-codegen-maven-plugin/etc/spotbugs/exclude.xml
  maven-plugins/snakeyaml-codegen-maven-plugin/pom.xml
  maven-plugins/stager-maven-plugin/etc/spotbugs/exclude.xml
  maven-plugins/stager-maven-plugin/pom.xml
  pom.xml
Labels: OCA Verified

#816 Archetype engine validation mechanism
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/Controller.java
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/InputResolver.java
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/ScriptLoader.java
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/ValidationException.java
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/VisitorAdapter.java
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/ast/Block.java
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/ast/Input.java
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/ast/Validation.java
  archetype/engine-v2/src/main/schema/archetype.xsd
  archetype/engine-v2/src/test/java/io/helidon/build/archetype/engine/v2/InputResolverTest.java
  archetype/engine-v2/src/test/java/io/helidon/build/archetype/engine/v2/ScriptLoaderTest.java
  archetype/engine-v2/src/test/java/io/helidon/build/archetype/engine/v2/TestHelper.java
  archetype/engine-v2/src/test/java/io/helidon/build/archetype/engine/v2/ast/ValidationTest.java
  archetype/engine-v2/src/test/resources/loader/validations.xml
  archetype/engine-v2/src/test/resources/validation/archetype-base.xml
  archetype/engine-v2/src/test/resources/validation/validations-all-in-one.xml
  archetype/engine-v2/src/test/resources/validation/validations.xml
  maven-plugins/helidon-archetype-maven-plugin/pom.xml
  maven-plugins/helidon-archetype-maven-plugin/src/it/projects/test5/expected.log
  maven-plugins/helidon-archetype-maven-plugin/src/it/projects/test5/invoker.properties
  maven-plugins/helidon-archetype-maven-plugin/src/it/projects/test5/pom.xml
  maven-plugins/helidon-archetype-maven-plugin/src/it/projects/test5/postbuild.groovy
  maven-plugins/helidon-archetype-maven-plugin/src/it/projects/test5/src/main/archetype/main.xml
  maven-plugins/helidon-archetype-maven-plugin/src/it/projects/test6/expected1.log
  maven-plugins/helidon-archetype-maven-plugin/src/it/projects/test6/expected2.log
  maven-plugins/helidon-archetype-maven-plugin/src/it/projects/test6/expected3.log
  maven-plugins/helidon-archetype-maven-plugin/src/it/projects/test6/invoker.properties
  maven-plugins/helidon-archetype-maven-plugin/src/it/projects/test6/pom.xml
  maven-plugins/helidon-archetype-maven-plugin/src/it/projects/test6/postbuild.groovy
  maven-plugins/helidon-archetype-maven-plugin/src/it/projects/test6/src/main/archetype/files/pom.xml
  maven-plugins/helidon-archetype-maven-plugin/src/main/java/io/helidon/build/maven/archetype/IntegrationTestMojo.java
  maven-plugins/helidon-archetype-maven-plugin/src/main/java/io/helidon/build/maven/archetype/JarMojo.java
  maven-plugins/helidon-archetype-maven-plugin/src/main/java/io/helidon/build/maven/archetype/Validation.java
  maven-plugins/helidon-archetype-maven-plugin/src/main/java/io/helidon/build/maven/archetype/Validator.java
  maven-plugins/helidon-archetype-maven-plugin/src/main/java/io/helidon/build/maven/archetype/config/Validation.java
  maven-plugins/helidon-archetype-maven-plugin/src/main/java/io/helidon/build/maven/archetype/config/package-info.java
  maven-plugins/helidon-archetype-maven-plugin/src/test/java/io/helidon/build/maven/archetype/ValidatorTest.java
  pom.xml
Labels: OCA Verified

#826 821 GitHub actions 2.x
  .github/workflows/validate.yml
  Jenkinsfile
  etc/scripts/pipeline-env.bat
  etc/scripts/pipeline-env.sh
  pom.xml
Labels: OCA Verified

#833 Fix RegexValidator
  maven-plugins/helidon-archetype-maven-plugin/src/main/java/io/helidon/build/maven/archetype/RegexValidator.java
  maven-plugins/helidon-archetype-maven-plugin/src/main/java/io/helidon/build/maven/archetype/Validator.java
  maven-plugins/helidon-archetype-maven-plugin/src/test/java/io/helidon/build/maven/archetype/ValidatorTest.java
Labels: bug, archetype, OCA Verified

#834 [2.x] re-enable spotbugs
  .github/workflows/validate.yml
  dev-loop/etc/spotbugs/exclude.xml
  dev-loop/pom.xml
  etc/scripts/spotbugs.sh
  helidon-archetype/engine/etc/spotbugs/exclude.xml
  helidon-archetype/engine/pom.xml
  helidon-archetype/maven-plugin/etc/spotbugs/exclude.xml
  helidon-archetype/maven-plugin/pom.xml
  helidon-cli/codegen/etc/spotbugs/exclude.xml
  helidon-cli/codegen/pom.xml
  helidon-cli/harness/etc/spotbugs/exclude.xml
  helidon-cli/harness/pom.xml
  helidon-cli/impl/etc/spotbugs/exclude.xml
  helidon-cli/impl/pom.xml
  helidon-cli/plugin/etc/spotbugs/exclude.xml
  helidon-cli/plugin/pom.xml
  helidon-linker/etc/spotbugs/exclude.xml
  helidon-linker/pom.xml
  licensing/etc/spotbugs/exclude.xml
  licensing/pom.xml
  pom.xml
  services-maven-plugin/etc/spotbugs/exclude.xml
  services-maven-plugin/pom.xml
  snakeyaml-codegen-maven-plugin/etc/spotbugs/exclude.xml
  snakeyaml-codegen-maven-plugin/pom.xml
  stager-maven-plugin/etc/spotbugs/exclude.xml
  stager-maven-plugin/pom.xml
  utils/etc/spotbugs/exclude.xml
  utils/pom.xml
Labels: OCA Verified

#830 Update changelog post 2.3.7 release
  helidon-cli/CHANGELOG.md
Labels: cli, OCA Verified

#832 Add a changelog entry for 3.0.2
  Jenkinsfile
  cli/CHANGELOG.md
Labels: OCA Verified
