Repository helidon-io/helidon-build-tools, pull requests merged in 2023-01, with the labels that each got.

#831 maven-enforcer-plugin rule to enforce native-image version
  common/common/src/main/java/io/helidon/build/common/PathFinder.java
  maven-plugins/enforcer-maven-plugin/pom.xml
  maven-plugins/enforcer-maven-plugin/src/main/java/io/helidon/build/maven/enforcer/EnforcerMojo.java
  maven-plugins/enforcer-maven-plugin/src/main/java/io/helidon/build/maven/enforcer/RuleFailure.java
  maven-plugins/enforcer-maven-plugin/src/main/java/io/helidon/build/maven/enforcer/nativeimage/EnforcerNativeImageException.java
  maven-plugins/enforcer-maven-plugin/src/main/java/io/helidon/build/maven/enforcer/nativeimage/NativeImageConfig.java
  maven-plugins/enforcer-maven-plugin/src/main/java/io/helidon/build/maven/enforcer/nativeimage/NativeImageRule.java
  maven-plugins/enforcer-maven-plugin/src/main/java/io/helidon/build/maven/enforcer/nativeimage/VersionConfig.java
  maven-plugins/enforcer-maven-plugin/src/main/java/io/helidon/build/maven/enforcer/nativeimage/package-info.java
  maven-plugins/enforcer-maven-plugin/src/test/java/io/helidon/build/maven/enforcer/nativeimage/NativeImageRuleTest.java
  maven-plugins/helidon-maven-plugin/src/main/java/io/helidon/build/maven/GraalNativeMojo.java
Labels: maven-plugin, OCA Verified

#841 Archetype: support if attribute in <exec> and <source>
  archetype/engine-v2/src/main/schema/archetype.xsd
  archetype/engine-v2/src/test/java/io/helidon/build/archetype/engine/v2/ControllerTest.java
  archetype/engine-v2/src/test/resources/controller/invocation.xml
Labels: enhancement, archetype, OCA Verified

#846 Update validate workflow to upload artifacts
  .github/workflows/validate.yml
Labels: OCA Verified

#847 Update validate workflow to upload artifacts
  .github/workflows/validate.yml
Labels: 2.x, OCA Verified

#853 Archetype JSON serializer fixes
  archetype/engine-v2-json/src/test/java/io/helidon/build/archetype/v2/json/ScriptSerializerTest.java
  archetype/engine-v2-json/src/test/resources/variables.xml
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/util/ClientCompiler.java
  archetype/engine-v2/src/main/schema/archetype.xsd
Labels: bug, archetype, 3.x, OCA Verified

#856 upgrade doxia to 1.11.1
  pom.xml
Labels: OCA Verified

#861 Replace usage of ImageInfo.inImageRuntimeCode
  cli/common/src/main/java/io/helidon/build/cli/common/ImageInfo.java
  cli/impl/pom.xml
  cli/impl/src/main/java/io/helidon/build/cli/impl/Helidon.java
  cli/impl/src/main/java/io/helidon/build/cli/impl/Plugins.java
  cli/impl/src/main/java/module-info.java
  pom.xml
Labels: cli, OCA Verified

#860 Remove usage of `picocli.jansi.graalvm.AnsiConsole.systemInstall()`
  common/ansi/pom.xml
  common/ansi/src/main/java/io/helidon/build/common/ansi/AnsiConsoleInstaller.java
  common/ansi/src/main/java/module-info.java
  pom.xml
Labels: cli, OCA Verified

#843 CLI Distribution
  cli/impl/pom.xml
  cli/impl/src/main/assembly/distribution.xml
  cli/impl/src/main/assembly/helidon
  cli/impl/src/main/assembly/helidon.bat
Labels: OCA Verified

#867 GitHub action tests fix
  .github/workflows/validate.yml
  archetype/engine-v2/src/main/schema/archetype.xsd
  cli/codegen/src/test/java/io/helidon/build/cli/codegen/CommandAPTest.java
  cli/tests/pom.xml
  etc/scripts/github-build.sh
Labels: OCA Verified

#870 Set posix file permissions during unzip
  common/common/src/main/java/io/helidon/build/common/FileUtils.java
Labels: OCA Verified

#872 Enable failing tests from pipeline refactor
  cli/codegen/src/test/java/io/helidon/build/cli/codegen/CommandAPTest.java
  cli/tests/functional/src/test/java/io/helidon/build/cli/tests/CliFunctionalV2Test.java
  cli/tests/functional/src/test/java/io/helidon/build/cli/tests/CliMavenTest.java
  cli/tests/pom.xml
Labels: OCA Verified

#864 Migrate from TSLint to ESLint
  ide-support/vscode-extension/.eslintrc.js
  ide-support/vscode-extension/package-lock.json
  ide-support/vscode-extension/package.json
  ide-support/vscode-extension/src/Context.ts
  ide-support/vscode-extension/src/Expression.ts
  ide-support/vscode-extension/src/FileSystemAPI.ts
  ide-support/vscode-extension/src/GeneratorCommand.ts
  ide-support/vscode-extension/src/Interpreter.ts
  ide-support/vscode-extension/src/VSCodeAPI.ts
  ide-support/vscode-extension/src/extension.ts
  ide-support/vscode-extension/src/generator.ts
  ide-support/vscode-extension/src/helidonDev.ts
  ide-support/vscode-extension/src/languageServer.ts
  ide-support/vscode-extension/src/launchConfiguration.ts
  ide-support/vscode-extension/src/logger.ts
  ide-support/vscode-extension/src/test/suite/OutputFormatter.test.ts
  ide-support/vscode-extension/src/test/suite/common.test.ts
  ide-support/vscode-extension/src/test/suite/extension.test.ts
  ide-support/vscode-extension/src/test/suite/generator.test.ts
  ide-support/vscode-extension/src/test/suite/helidonDev.test.ts
  ide-support/vscode-extension/src/validationApi.ts
  ide-support/vscode-extension/tslint.json
  ide-support/vscode-extension/webpack.config.js
Labels: OCA Verified

#874 Github Action: windows build
  .github/workflows/validate.yml
  cli/tests/functional/src/test/java/io/helidon/build/cli/tests/CliMavenTest.java
  etc/scripts/build.bat
Labels: OCA Verified

#865 CLI distribution tests
  cli/tests/functional/src/test/java/io/helidon/build/cli/tests/CliDistributionTest.java
Labels: cli, OCA Verified, testing
