Repository helidon-io/helidon-build-tools, pull requests merged in 2023-07, with the labels that each got.

#947 Improve layout of helidon.zip
  cli/impl/pom.xml
  cli/impl/src/main/assembly/distribution.xml
  cli/impl/src/main/assembly/helidon
  cli/impl/src/main/assembly/helidon.bat
  cli/tests/functional/src/test/java/io/helidon/build/cli/tests/CliDistributionTest.java
Labels: cli, 3.x, OCA Verified

#948 Fix prerelease version prompt order
  cli/common/src/main/java/io/helidon/build/cli/common/ArchetypesData.java
  cli/common/src/main/java/io/helidon/build/cli/common/ArchetypesDataLoader.java
  cli/common/src/main/java/io/helidon/build/cli/common/SemVer.java
  cli/common/src/test/java/io/helidon/build/cli/common/ArchetypesDataTest.java
  cli/common/src/test/java/io/helidon/build/cli/common/SemVerTest.java
  cli/impl/src/main/java/io/helidon/build/cli/impl/InitCommand.java
  cli/impl/src/test/java/io/helidon/build/cli/impl/InitCommandTest.java
  cli/impl/src/test/resources/io/helidon/build/cli/impl/input-full-version-list.txt
  cli/impl/src/test/resources/io/helidon/build/cli/impl/input-latest-version-list.txt
  cli/impl/src/test/resources/versions/cli-data/versions.xml
Labels: cli, 3.x, OCA Verified

#951 handle default and latest version correctly in cache/info
  cli/impl/etc/spotbugs/exclude.xml
  cli/impl/src/main/java/io/helidon/build/cli/impl/InfoCommand.java
  cli/impl/src/main/java/io/helidon/build/cli/impl/Metadata.java
  cli/impl/src/main/java/io/helidon/build/cli/impl/VersionCommand.java
  cli/plugin/src/main/java/io/helidon/build/cli/plugin/UpdateMetadata.java
  cli/tests/functional/src/test/java/io/helidon/build/cli/tests/CliFunctionalV2Test.java
Labels: OCA Verified

#953 add a cli changelog entry for 3.0.5
  cli/CHANGELOG.md
Labels: OCA Verified

#952 Remove dependency on ArchetypesData in cli plugin
  cli/common/src/main/java/io/helidon/build/cli/common/ArchetypesData.java
  cli/impl/pom.xml
  cli/impl/src/main/java/io/helidon/build/cli/impl/CommandRequirements.java
  cli/impl/src/main/java/io/helidon/build/cli/impl/CommonOptions.java
  cli/impl/src/main/java/io/helidon/build/cli/impl/InitCommand.java
  cli/impl/src/main/java/io/helidon/build/cli/impl/Metadata.java
  cli/impl/src/test/java/io/helidon/build/cli/impl/MetadataTest.java
  cli/impl/src/test/java/io/helidon/build/cli/impl/MetadataTestBase.java
  cli/impl/src/test/java/io/helidon/build/cli/impl/MetadataTestIT.java
  cli/impl/src/test/java/io/helidon/build/cli/impl/MetadataTestServer.java
  cli/impl/src/test/java/io/helidon/build/cli/impl/TestMetadata.java
  cli/plugin/pom.xml
  cli/plugin/src/main/java/io/helidon/build/cli/plugin/UpdateBase.java
  cli/plugin/src/main/java/io/helidon/build/cli/plugin/UpdateMetadata.java
  cli/plugin/src/main/java/io/helidon/build/cli/plugin/UpdateVersion.java
  cli/plugin/src/main/java/io/helidon/build/cli/plugin/UpdateVersions.java
  cli/plugin/src/main/java/module-info.java
  cli/tests/functional/src/test/java/io/helidon/build/cli/tests/CliFunctionalV2Test.java
  cli/tests/functional/src/test/java/io/helidon/build/cli/tests/CliMavenTest.java
  common/common/src/main/java/io/helidon/build/common/FileUtils.java
  pom.xml
Labels: OCA Verified

#956 Switch to Smallrye Jandex to align with Helidon.
  linker/pom.xml
  linker/src/main/java/module-info.java
  pom.xml
Labels: JLink, OCA Verified

#959 Issue #955 - Fix org.apache.maven dependencies in maven plugins
  common/maven-plugin/pom.xml
  maven-plugins/enforcer-maven-plugin/pom.xml
  maven-plugins/helidon-archetype-maven-plugin/pom.xml
  maven-plugins/helidon-cli-maven-plugin/pom.xml
  maven-plugins/helidon-maven-plugin/pom.xml
  maven-plugins/services-maven-plugin/pom.xml
  maven-plugins/sitegen-maven-plugin/pom.xml
  maven-plugins/snakeyaml-codegen-maven-plugin/pom.xml
  maven-plugins/stager-maven-plugin/pom.xml
Labels: OCA Verified

#963 Minor VSCode plugin updates
  ide-support/lsp/common/pom.xml
  ide-support/lsp/helidon-lsp-maven-plugin/pom.xml
  ide-support/lsp/lsp-server/etc/logging.properties
  ide-support/lsp/lsp-server/pom.xml
  ide-support/lsp/lsp-server/src/main/java/io/helidon/lsp/server/HelidonLSPLauncher.java
  ide-support/lsp/lsp-server/src/main/java/io/helidon/lsp/server/management/MavenSupport.java
  ide-support/lsp/lsp-server/src/main/java/io/helidon/lsp/server/util/LanguageClientLogUtil.java
  ide-support/lsp/lsp-server/src/main/resources/version.properties
  ide-support/lsp/lsp-server/src/test/java/io/helidon/lsp/server/management/MavenSupportTest.java
  ide-support/lsp/lsp-server/src/test/resources/pomTests/withMain/pom.xml
  ide-support/lsp/lsp-server/src/test/resources/pomTests/withoutMain/pom.xml
  ide-support/lsp/pom.xml
  ide-support/pom.xml
  ide-support/vscode-extension/.eslintrc.js
  ide-support/vscode-extension/assets/start_page.html
  ide-support/vscode-extension/gulpfile.js
  ide-support/vscode-extension/package-lock.json
  ide-support/vscode-extension/package.json
  ide-support/vscode-extension/pom.xml
  ide-support/vscode-extension/src/ChildProcessAPI.ts
  ide-support/vscode-extension/src/FileSystemAPI.ts
  ide-support/vscode-extension/src/GeneratorCommand.ts
  ide-support/vscode-extension/src/OutputFormatter.ts
  ide-support/vscode-extension/src/ProjectInformation.ts
  ide-support/vscode-extension/src/VSCodeAPI.ts
  ide-support/vscode-extension/src/common.ts
  ide-support/vscode-extension/src/extension.ts
  ide-support/vscode-extension/src/generator.ts
  ide-support/vscode-extension/src/helidonDev.ts
  ide-support/vscode-extension/src/languageServer.ts
  ide-support/vscode-extension/src/launchConfiguration.ts
  ide-support/vscode-extension/src/logger.ts
  ide-support/vscode-extension/src/propertiesSupport.ts
  ide-support/vscode-extension/src/startPage.ts
  ide-support/vscode-extension/src/test/runTest.ts
  ide-support/vscode-extension/src/test/suite/OutputFormatter.test.ts
  ide-support/vscode-extension/src/test/suite/common.test.ts
  ide-support/vscode-extension/src/test/suite/extension.test.ts
  ide-support/vscode-extension/src/test/suite/generator.test.ts
  ide-support/vscode-extension/src/test/suite/helidonDev.test.ts
  ide-support/vscode-extension/src/test/suite/index.ts
  ide-support/vscode-extension/src/validationApi.ts
  ide-support/vscode-extension/webpack.config.js
  pom.xml
Labels: OCA Verified
