Repository helidon-io/helidon-build-tools, pull requests merged in 2023-05, with the labels that each got.

#926 Access global options value from CommandContext
  cli/harness/src/main/java/io/helidon/build/cli/harness/CommandContext.java
  cli/harness/src/main/java/io/helidon/build/cli/harness/CommandParser.java
  cli/harness/src/main/java/io/helidon/build/cli/harness/GlobalOptions.java
  cli/harness/src/test/java/io/helidon/build/cli/harness/CommandParserTest.java
  cli/impl/src/main/java/io/helidon/build/cli/impl/CommonOptions.java
  cli/impl/src/main/java/io/helidon/build/cli/impl/InfoCommand.java
Labels: OCA Verified

#916 create shellcheck github action
  .github/workflows/validate.yml
  cli/impl/helidon.sh
  dev-loop/dev-loop/helidon
  etc/scripts/build-cli.sh
  etc/scripts/build.sh
  etc/scripts/checkstyle.sh
  etc/scripts/copyright.sh
  etc/scripts/github-build.sh
  etc/scripts/release.sh
  etc/scripts/shellcheck.sh
  etc/scripts/spotbugs.sh
  linker/src/main/resources/start-template.sh
Labels: OCA Verified

#905 List versions in helidon init
  cli/README.md
  cli/common/src/main/java/io/helidon/build/cli/common/ArchetypesData.java
  cli/common/src/main/java/io/helidon/build/cli/common/ArchetypesDataLoader.java
  cli/common/src/main/java/io/helidon/build/cli/common/SemVer.java
  cli/common/src/main/java/module-info.java
  cli/common/src/test/java/io/helidon/build/cli/common/ArchetypesDataLoaderTest.java
  cli/common/src/test/java/io/helidon/build/cli/common/ArchetypesDataTest.java
  cli/common/src/test/java/io/helidon/build/cli/common/SemVerTest.java
  cli/common/src/test/resources/versions/cli-data/4.0.0-SNAPSHOT/cli-data.zip
  cli/common/src/test/resources/versions/cli-data/versions.xml
  cli/impl/src/main/java/io/helidon/build/cli/impl/InitCommand.java
  cli/impl/src/main/java/io/helidon/build/cli/impl/Metadata.java
  cli/impl/src/main/java/module-info.java
  cli/impl/src/test/java/io/helidon/build/cli/impl/InitCommandTest.java
  cli/impl/src/test/java/io/helidon/build/cli/impl/MetadataTest.java
  cli/impl/src/test/java/io/helidon/build/cli/impl/MetadataTestBase.java
  cli/impl/src/test/java/io/helidon/build/cli/impl/MetadataTestIT.java
  cli/impl/src/test/java/io/helidon/build/cli/impl/MetadataTestServer.java
  cli/impl/src/test/java/io/helidon/build/cli/impl/TestMetadata.java
  cli/impl/src/test/resources/cli-data/versions.xml
  cli/impl/src/test/resources/io/helidon/build/cli/impl/input-full-version-list.txt
  cli/impl/src/test/resources/io/helidon/build/cli/impl/input-latest-version-list.txt
  cli/impl/src/test/resources/versions/cli-data/4.0.0-SNAPSHOT/cli-data.zip
  cli/impl/src/test/resources/versions/cli-data/versions.xml
  cli/plugin/src/main/java/io/helidon/build/cli/plugin/UpdateMetadata.java
  cli/tests/functional/src/it/projects/archetype-v2/cli/versions.xml.mustache
  cli/tests/functional/src/it/projects/archetype-v2/pom.xml
  cli/tests/functional/src/test/java/io/helidon/build/cli/tests/CliDistributionTest.java
  common/common/src/main/java/io/helidon/build/common/Lists.java
  common/common/src/main/java/io/helidon/build/common/Maps.java
  common/maven/src/main/java/io/helidon/build/common/maven/VersionRange.java
Labels: OCA Verified

#929 Make the archetype engine compatible with current archetype
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/BatchInputResolver.java
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/Controller.java
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/MergedModel.java
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/ModelResolver.java
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/MustacheSupport.java
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/TerminalInputResolver.java
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/ast/DeclaredValue.java
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/ast/Input.java
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/ast/Model.java
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/context/Context.java
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/context/ContextNode.java
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/context/ContextRegistry.java
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/context/ContextScope.java
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/context/CopyOnWriteContextEdge.java
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/util/ArchetypeValidator.java
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/util/InputPermutations.java
  archetype/engine-v2/src/test/java/io/helidon/build/archetype/engine/v2/ArchetypeEngineV2Test.java
  archetype/engine-v2/src/test/java/io/helidon/build/archetype/engine/v2/InputResolverTest.java
  archetype/engine-v2/src/test/java/io/helidon/build/archetype/engine/v2/MustacheSupportTest.java
  archetype/engine-v2/src/test/resources/generator/context-values.xml
Labels: OCA Verified

#933 Enforcer plugin correctly handle MacOS case insensitive paths
  maven-plugins/enforcer-maven-plugin/src/main/java/io/helidon/build/maven/enforcer/EnforcerMojo.java
  maven-plugins/enforcer-maven-plugin/src/main/java/io/helidon/build/maven/enforcer/FileFinder.java
  maven-plugins/enforcer-maven-plugin/src/main/java/io/helidon/build/maven/enforcer/FileRequest.java
  maven-plugins/enforcer-maven-plugin/src/main/java/io/helidon/build/maven/enforcer/FoundFiles.java
  maven-plugins/enforcer-maven-plugin/src/main/java/io/helidon/build/maven/enforcer/GitCommands.java
Labels: maven-plugin, OCA Verified

#935 Fix xml2js is vulnerable to prototype pollution
  ide-support/vscode-extension/package-lock.json
  ide-support/vscode-extension/package.json
Labels: OCA Verified

#937 Fix npm build for vscode plugin.
  Jenkinsfile
  ide-support/vscode-extension/package.json
  ide-support/vscode-extension/pom.xml
Labels: bug, OCA Verified, vscode
