Repository helidon-io/helidon-build-tools, pull requests merged in 2023-02, with the labels that each got.

#876 Add unit test for FileUtils
  common/common/src/main/java/io/helidon/build/common/FileUtils.java
  common/common/src/test/java/io/helidon/build/common/FileUtilsTest.java
Labels: OCA Verified, testing

#837 Align naming with inclusive naming
  maven-plugins/enforcer-maven-plugin/pom.xml
  maven-plugins/enforcer-maven-plugin/src/it/projects/example/pom.xml
  maven-plugins/enforcer-maven-plugin/src/it/projects/example/src/main/resources/additionalTerm.txt
  maven-plugins/enforcer-maven-plugin/src/it/projects/example/src/main/resources/default.txt
  maven-plugins/enforcer-maven-plugin/src/it/projects/example/src/main/resources/excludedFile.txt
  maven-plugins/enforcer-maven-plugin/src/it/projects/example/src/main/resources/excludedTerm.txt
  maven-plugins/enforcer-maven-plugin/src/it/settings.xml
  maven-plugins/enforcer-maven-plugin/src/main/java/io/helidon/build/maven/enforcer/EnforcerMojo.java
  maven-plugins/enforcer-maven-plugin/src/main/java/io/helidon/build/maven/enforcer/inclusivenaming/InclusiveNamingRule.java
  maven-plugins/enforcer-maven-plugin/src/main/java/io/helidon/build/maven/enforcer/inclusivenaming/InlusiveNamingConfig.java
  maven-plugins/enforcer-maven-plugin/src/main/java/io/helidon/build/maven/enforcer/inclusivenaming/XmlData.java
  maven-plugins/enforcer-maven-plugin/src/main/java/io/helidon/build/maven/enforcer/inclusivenaming/XmlInclusiveNaming.java
  maven-plugins/enforcer-maven-plugin/src/main/java/io/helidon/build/maven/enforcer/inclusivenaming/package-info.java
  maven-plugins/enforcer-maven-plugin/src/main/resources/io/helidon/build/maven/enforcer/inclusivenaming/inclusive-names.xml
Labels: maven-plugin, OCA Verified

#882 Fix doc search result location
  maven-plugins/sitegen-maven-plugin/src/main/resources/templates/vuetify/search_index.ftl
Labels: OCA Verified

#884 Fix archetype optimizer and JSON serializer
  archetype/engine-v2-json/src/main/java/io/helidon/build/archetype/v2/json/ScriptSerializer.java
  archetype/engine-v2-json/src/test/java/io/helidon/build/archetype/v2/json/ScriptSerializerTest.java
  archetype/engine-v2-json/src/test/resources/empty-method/main.xml
  archetype/engine-v2-json/src/test/resources/expected/empty-method.json
  archetype/engine-v2-json/src/test/resources/expected/empty.json
  archetype/engine-v2-json/src/test/resources/expected/filtering1.json
  archetype/engine-v2-json/src/test/resources/filtering1/main.xml
  archetype/engine-v2-json/src/test/resources/filtering2/main.xml
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/util/ArchetypeScanner.java
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/util/OptimizedWalker.java
  archetype/engine-v2/src/test/java/io/helidon/build/archetype/engine/v2/util/ClientCompilerTest.java
  archetype/engine-v2/src/test/resources/compiler/empty-method/main.xml
  archetype/engine-v2/src/test/resources/compiler/filtering1/main.xml
  archetype/engine-v2/src/test/resources/compiler/filtering2/main.xml
  archetype/engine-v2/src/test/resources/compiler/filtering3/main.xml
  archetype/engine-v2/src/test/resources/compiler/filtering3/script1.xml
  archetype/engine-v2/src/test/resources/compiler/filtering3/script2.xml
Labels: archetype, OCA Verified

#885 Add a changelog entry for 3.0.4
  cli/CHANGELOG.md
Labels: OCA Verified

#886 VSCode fixes
  ide-support/lsp/lsp-server/src/main/java/io/helidon/lsp/server/core/HelidonLanguageServer.java
  ide-support/lsp/lsp-server/src/main/java/io/helidon/lsp/server/core/HelidonTextDocumentService.java
  ide-support/lsp/lsp-server/src/main/java/io/helidon/lsp/server/core/LanguageServerContext.java
  ide-support/lsp/lsp-server/src/main/java/io/helidon/lsp/server/management/MavenSupport.java
  ide-support/lsp/lsp-server/src/main/java/io/helidon/lsp/server/service/ContentManager.java
  ide-support/lsp/lsp-server/src/main/java/io/helidon/lsp/server/service/config/ConfigurationPropertiesService.java
  ide-support/lsp/lsp-server/src/main/java/io/helidon/lsp/server/service/config/properties/PropertiesTextDocumentHandler.java
  ide-support/lsp/lsp-server/src/main/java/io/helidon/lsp/server/service/config/yaml/YamlTextDocumentHandler.java
  ide-support/lsp/lsp-server/src/main/java/io/helidon/lsp/server/util/LanguageClientLogUtil.java
  ide-support/lsp/lsp-server/src/main/java/io/helidon/lsp/server/util/package-info.java
  ide-support/vscode-extension/README.md
  ide-support/vscode-extension/assets/start_page.html
  ide-support/vscode-extension/images/generator_helidon_version.png
  ide-support/vscode-extension/images/helidon_command_palette.png
  ide-support/vscode-extension/package-lock.json
  ide-support/vscode-extension/package.json
  ide-support/vscode-extension/src/VSCodeAPI.ts
  ide-support/vscode-extension/src/common.ts
  ide-support/vscode-extension/src/generator.ts
  ide-support/vscode-extension/src/helidonDev.ts
  ide-support/vscode-extension/src/languageServer.ts
  ide-support/vscode-extension/src/test/suite/generator.test.ts
  ide-support/vscode-extension/src/test/suite/helidonDev.test.ts
Labels: OCA Verified

#836 add props-file option to save user inputs during project generation
  archetype/engine-v2/etc/spotbugs/exclude.xml
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/ArchetypeEngineV2.java
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/context/ContextPrinter.java
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/context/ContextSerializer.java
  archetype/engine-v2/src/test/java/io/helidon/build/archetype/engine/v2/ArchetypeEngineV2Test.java
  archetype/engine-v2/src/test/java/io/helidon/build/archetype/engine/v2/context/ContextSerializerTest.java
  cli/harness/src/main/java/io/helidon/build/cli/harness/CommandModel.java
  cli/harness/src/main/java/io/helidon/build/cli/harness/CommandParameters.java
  cli/harness/src/main/java/io/helidon/build/cli/harness/CommandParser.java
  cli/harness/src/main/java/io/helidon/build/cli/harness/GlobalOptions.java
  cli/harness/src/main/java/io/helidon/build/cli/harness/UsageCommand.java
  cli/harness/src/test/java/io/helidon/build/cli/harness/CommandParserTest.java
  cli/harness/src/test/resources/io/helidon/build/cli/harness/cli-usage.txt
  cli/harness/src/test/resources/io/helidon/build/cli/harness/help-cmd-help.txt
  cli/harness/src/test/resources/io/helidon/build/cli/harness/simple-cmd-help.txt
  cli/harness/src/test/resources/io/helidon/build/cli/harness/test-props-file.properties
  cli/impl/etc/spotbugs/exclude.xml
  cli/impl/src/main/java/io/helidon/build/cli/impl/ArchetypeInvoker.java
  cli/impl/src/main/java/io/helidon/build/cli/impl/CommonOptions.java
  cli/impl/src/main/java/io/helidon/build/cli/impl/InitCommand.java
  cli/impl/src/main/java/io/helidon/build/cli/impl/InitOptions.java
  cli/impl/src/test/java/io/helidon/build/cli/impl/ArchetypeInvokerTest.java
  common/common/etc/spotbugs/exclude.xml
  common/common/src/main/java/io/helidon/build/common/FileUtils.java
  maven-plugins/helidon-archetype-maven-plugin/src/main/java/io/helidon/build/maven/archetype/IntegrationTestMojo.java
  maven-plugins/helidon-archetype-maven-plugin/src/main/java/io/helidon/build/maven/archetype/postgenerate/EngineFacade.java
  maven-plugins/helidon-archetype-maven-plugin/src/main/java/io/helidon/build/maven/archetype/postgenerate/ReflectedEngine.java
  maven-plugins/helidon-archetype-maven-plugin/src/test/java/io/helidon/build/maven/archetype/postgenerate/ReflectedEngineTest.java
Labels: OCA Verified

#888 improve search of a pom.xml in VSCode extension
  ide-support/lsp/lsp-server/src/main/java/io/helidon/lsp/server/management/MavenSupport.java
  ide-support/lsp/lsp-server/src/test/java/io/helidon/lsp/server/management/MavenSupportTest.java
  ide-support/lsp/lsp-server/src/test/resources/pomTests/withMain/pom.xml
  ide-support/lsp/lsp-server/src/test/resources/pomTests/withMain/src/main/test.txt
  ide-support/lsp/lsp-server/src/test/resources/pomTests/withoutMain/pom.xml
  ide-support/lsp/lsp-server/src/test/resources/pomTests/withoutMain/src/test.txt
Labels: OCA Verified
