Repository helidon-io/helidon-build-tools, pull requests merged in 2023-09, with the labels that each got.

#983 Fix ClassNotFoundException during `mvn archetype:generate`
  maven-plugins/helidon-archetype-maven-plugin/src/main/java/io/helidon/build/maven/archetype/postgenerate/ReflectedEngine.java
Labels: maven-plugin, OCA Verified

#984 3.x Fix ClassNotFound exception from reflection logic
  maven-plugins/helidon-archetype-maven-plugin/src/main/java/io/helidon/build/maven/archetype/postgenerate/ReflectedEngine.java
Labels: maven-plugin, 3.x, OCA Verified

#982 support for jakarta and javax violations maven enforcer rule
  maven-enforcer-rules/README.md
  maven-enforcer-rules/etc/spotbugs/exclude.xml
  maven-enforcer-rules/pom.xml
  maven-enforcer-rules/src/main/java/io/helidon/build/maven/enforcer/rules/DependencyIsValidCheck.java
  maven-enforcer-rules/src/main/java/io/helidon/build/maven/enforcer/rules/HelidonDependenciesRule.java
  maven-enforcer-rules/src/main/java/io/helidon/build/maven/enforcer/rules/ViolationException.java
  maven-enforcer-rules/src/main/java/io/helidon/build/maven/enforcer/rules/package-info.java
  maven-enforcer-rules/src/main/resources/jakarta-groups.properties
  maven-enforcer-rules/src/main/resources/jakarta-renamed.properties
  maven-enforcer-rules/src/main/resources/jakarta-versions.properties
  maven-enforcer-rules/src/test/java/io/helidon/build/maven/enforcer/rules/DependencyIsValidCheckTest.java
  maven-enforcer-rules/src/test/java/io/helidon/build/maven/enforcer/rules/HelidonDependencyRuleTest.java
  pom.xml
Labels: OCA Verified

#985 Improve Maven archetype compatibility testing to prevent uncaught cla…
  cli/tests/functional/src/it/settings.xml
  dev-loop/dev-loop/src/it/settings.xml
  maven-plugins/build-cache-maven-plugin/src/it/settings.xml
  maven-plugins/enforcer-maven-plugin/src/it/settings.xml
  maven-plugins/helidon-archetype-maven-plugin/etc/spotbugs/exclude.xml
  maven-plugins/helidon-archetype-maven-plugin/pom.xml
  maven-plugins/helidon-archetype-maven-plugin/src/it/settings.xml
  maven-plugins/helidon-archetype-maven-plugin/src/main/java/io/helidon/build/maven/archetype/IntegrationTestMojo.java
  maven-plugins/helidon-archetype-maven-plugin/src/main/java/io/helidon/build/maven/archetype/JarMojo.java
  maven-plugins/helidon-archetype-maven-plugin/src/main/java/io/helidon/build/maven/archetype/MavenArchetypeGenerator.java
  maven-plugins/helidon-archetype-maven-plugin/src/main/java/io/helidon/build/maven/archetype/MojoHelper.java
  maven-plugins/helidon-archetype-maven-plugin/src/main/java/io/helidon/build/maven/archetype/PluginContainerManager.java
  maven-plugins/helidon-archetype-maven-plugin/src/main/java/io/helidon/build/maven/archetype/ReflectionHelper.java
  maven-plugins/helidon-maven-plugin/src/it/settings.xml
  maven-plugins/stager-maven-plugin/src/it/settings.xml
Labels: OCA Verified

#986 Maven archetype compat testing improvement 3.x
  cli/tests/functional/src/it/settings.xml
  dev-loop/dev-loop/src/it/settings.xml
  maven-plugins/build-cache-maven-plugin/src/it/settings.xml
  maven-plugins/enforcer-maven-plugin/src/it/settings.xml
  maven-plugins/helidon-archetype-maven-plugin/etc/spotbugs/exclude.xml
  maven-plugins/helidon-archetype-maven-plugin/pom.xml
  maven-plugins/helidon-archetype-maven-plugin/src/it/settings.xml
  maven-plugins/helidon-archetype-maven-plugin/src/main/java/io/helidon/build/maven/archetype/IntegrationTestMojo.java
  maven-plugins/helidon-archetype-maven-plugin/src/main/java/io/helidon/build/maven/archetype/JarMojo.java
  maven-plugins/helidon-archetype-maven-plugin/src/main/java/io/helidon/build/maven/archetype/MavenArchetypeGenerator.java
  maven-plugins/helidon-archetype-maven-plugin/src/main/java/io/helidon/build/maven/archetype/MojoHelper.java
  maven-plugins/helidon-archetype-maven-plugin/src/main/java/io/helidon/build/maven/archetype/PluginContainerManager.java
  maven-plugins/helidon-archetype-maven-plugin/src/main/java/io/helidon/build/maven/archetype/ReflectionHelper.java
  maven-plugins/helidon-maven-plugin/src/it/settings.xml
  maven-plugins/stager-maven-plugin/src/it/settings.xml
Labels: OCA Verified
