Repository helidon-io/helidon-build-tools, pull requests merged in 2023-03, with the labels that each got.

#890 Add CLI release readme
  etc/RELEASE.md
Labels: cli, docs, OCA Verified

#893 Fix failing build on Linux and Windows
  archetype/engine-v2/src/test/java/io/helidon/build/archetype/engine/v2/context/ContextPrinterTest.java
  cli/harness/src/test/java/io/helidon/build/cli/harness/CommandParserTest.java
  cli/tests/functional/src/it/projects/archetype-v2/pom.xml
  cli/tests/functional/src/test/java/io/helidon/build/cli/tests/FunctionalUtils.java
  cli/tests/pom.xml
  common/common/src/main/java/io/helidon/build/common/FileUtils.java
  dev-loop/dev-loop/src/test/java/io/helidon/build/devloop/BuildRootTestIT.java
  etc/scripts/build.bat
  maven-plugins/build-cache-maven-plugin/src/it/projects/test1/expected.log
  maven-plugins/build-cache-maven-plugin/src/it/projects/test1/pom.xml
  maven-plugins/stager-maven-plugin/pom.xml
  maven-plugins/stager-maven-plugin/src/it/projects/archive/postbuild.groovy
  maven-plugins/stager-maven-plugin/src/it/projects/template/postbuild.groovy
  maven-plugins/stager-maven-plugin/src/test/java/io/helidon/build/maven/stager/ProjectsTestIT.java
Labels: OCA Verified

#904 Fix GitIgnore on Windows.
  maven-plugins/enforcer-maven-plugin/src/main/java/io/helidon/build/maven/enforcer/GitIgnore.java
Labels: OCA Verified

#907 Fix CommandParserTest.testPropsFileOptionWithExistingFile on windows
  cli/harness/pom.xml
  cli/harness/src/test/java/io/helidon/build/cli/harness/CommandParserTest.java
Labels: OCA Verified, testing

#910 Refactor distribution for SDKMan
  cli/impl/src/main/assembly/distribution.xml
  cli/tests/functional/src/test/java/io/helidon/build/cli/tests/CliDistributionTest.java
Labels: cli, OCA Verified

#889 Expose context values as template model
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/MustacheSupport.java
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/context/ContextNode.java
  archetype/engine-v2/src/test/java/io/helidon/build/archetype/engine/v2/OutputGeneratorTest.java
  archetype/engine-v2/src/test/java/io/helidon/build/archetype/engine/v2/context/ContextNodeTest.java
  archetype/engine-v2/src/test/resources/generator/context-values.mustache
  archetype/engine-v2/src/test/resources/generator/context-values.xml
Labels: OCA Verified

#911 fix helidon-cli-functional module test
  cli/impl/pom.xml
  cli/tests/functional/pom.xml
  cli/tests/functional/src/test/java/io/helidon/build/cli/tests/CliFunctionalV2Test.java
  cli/tests/functional/src/test/java/io/helidon/build/cli/tests/CliMavenTest.java
  cli/tests/pom.xml
Labels: OCA Verified, testing

#913 Fix testMultipleChangesDetected on windows
  dev-loop/dev-loop/src/test/java/io/helidon/build/devloop/BuildRootTestIT.java
Labels: OCA Verified, testing
