Repository helidon-io/helidon-build-tools, pull requests merged in 2023-04, with the labels that each got.

#919 Additional mustache unit test
  archetype/engine-v2/src/test/java/io/helidon/build/archetype/engine/v2/MustacheSupportTest.java
Labels: OCA Verified, testing

#922 GitHub action based CI
  .github/workflows/validate.yml
  Jenkinsfile
  etc/scripts/pipeline-env.sh
  pom.xml
Labels: OCA Verified, 1.x

#920 Archetype model value override
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/MergedModel.java
  archetype/engine-v2/src/test/java/io/helidon/build/archetype/engine/v2/ArchetypeEngineV2Test.java
  archetype/engine-v2/src/test/java/io/helidon/build/archetype/engine/v2/InputResolverTest.java
  archetype/engine-v2/src/test/java/io/helidon/build/archetype/engine/v2/MustacheSupportTest.java
Labels: OCA Verified, compatibility

#914 always display Helidon version in init command
  cli/impl/src/main/java/io/helidon/build/cli/impl/InitCommand.java
Labels: OCA Verified

#923 MergedModel.resolveModel should not require the root scope
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/ArchetypeEngineV2.java
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/Controller.java
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/MergedModel.java
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/context/Context.java
  archetype/engine-v2/src/test/java/io/helidon/build/archetype/engine/v2/MergedModelTest.java
Labels: OCA Verified

#924 Archetype templates scoped model is not merged with global model
  archetype/engine-v2/src/main/java/io/helidon/build/archetype/engine/v2/OutputGenerator.java
  archetype/engine-v2/src/test/java/io/helidon/build/archetype/engine/v2/OutputGeneratorTest.java
  archetype/engine-v2/src/test/resources/generator/templates-override.xml
Labels: archetype, 3.x, OCA Verified, compatibility
